Provider netcup
qdm12/ddns-updater pull request #361
Opened 2022-09-07 11:03 UTC by Azorimor

This PR adds basic support to use [Netcup](https://netcup.eu) as provider. The implementation only updates the IP of the given host. Additional settings (TTL, Retry, Refresh, ...) can be set manually in the netcup customercontrolpanel / dashboard.

All requests to the netcup api are send to the same endpoint. The different functions are defined by the body of the request. For example the following requests (and more) are necessary. (see [doc](https://www.netcup-wiki.de/wiki/DNS_API)) The requests are implemented in netcup/client.go.

Login (Create Session on server, which is valid for 15 minutes (logout not implemented, because 15 min as default seems ok))
body:
```json
"action": "login",
"param": {
  "customernumber": "111",
  "apikey": "xxxxx",
  "apipassword": "yyyy"
}
```

2022-09-16 22:19 UTC, qdm12 requested changes
Thank you! 👍 

I requested quite a bit of code changes, feel free to let me know if you don't have the time/will to do it and I can pick it up from your fork and finish it up myself as well, and you can test it after modifications. If you want to do it, feel free to comment and I'll wait for you no problem (I'm also moving out/in so quite busy over here)

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/provider.go
> +	record, err := nc.GetRecordToUpdate(ctx, p.domain, p.host, ip)
nit since we dereference record below, we should return a value instead of a pointer

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/dnsrecord.go
> +}
No need for a constructor, just assign the struct directly

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/provider.go
> +		return nil, err
```suggestion
		return nil, fmt.Errorf("updating DNS records: %w", err)
```

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/provider.go
> +		return nil, err
```suggestion
		return nil, fmt.Errorf("decoding response data: %w", err)
```

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/provider.go
> +	var returnedUpdated = result.GetRecord(p.host, recordType)
nit

```suggestion

	returnedUpdated := result.GetRecord(p.host, recordType)
```

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/provider.go
> +	var destination = returnedUpdated.Destination
nit

```suggestion
	destination := returnedUpdated.Destination
```

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/provider.go
> +		return nil, fmt.Errorf("%w: %s", errors.ErrIPReceivedMismatch, newIP.String())
```suggestion
		return nil, fmt.Errorf("%w: expected %s but received %s", errors.ErrIPReceivedMismatch, ip, newIP)
```

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/provider.go
> +		return errors.ErrHostWildcard
Precise in the documentation it cannot be a wildcard.
Also precise it can be `@`

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/provider.go
> +		return nil, err
```suggestion
		return nil, fmt.Errorf("configuration is not valid: %w", err)
```

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/provider.go
> +		return nil, err
```suggestion
		return nil, fmt.Errorf("decoding configuration: %w", err)
```

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/dnsrecord.go
> +type DNSRecordSet struct {
unexport as `dnsRecordSet`

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/dnsrecord.go
> +type DNSRecord struct {
unexport as `dnsRecord` (you can usually use `F2` key to rename with an IDE)

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/dnsrecord.go
> +	Type         string `json:"type"`
Are we using each of these fields? Unused fields should be removed.

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/dnsrecord.go
> +}
A constructor feels unneeded, just create the struct directly without a constructor function

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/dnsrecord.go
> +			return &record
return a value, not a ptr, there is no need for a ptr

```suggestion
func (r *DNSRecordSet) GetRecord(name, dnstype string) DNSRecord {
	for _, record := range r.DNSRecords {
		if record.Hostname == name && record.Type == dnstype {
			return record
```

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/dnsrecord.go
> +func (r *DNSRecordSet) GetRecordOccurences(hostname, dnstype string) int {
unexport

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/dnsrecord.go
> +func (r *DNSRecordSet) GetRecord(name, dnstype string) *DNSRecord {
unexport

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/dnsrecord.go
> +	return result
nit use named return to your advantage (and also `occurences`  is more meaningful than `result` 😉)

```suggestion
func (r *DNSRecordSet) GetRecordOccurences(hostname, dnstype string) (occurrences uint) {
	for _, record := range r.DNSRecords {
		if record.Hostname == hostname && record.Type == dnstype {
			occurrences++
		}
	}
	return occurrences
```

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/client.go
> +		return nil, err
```suggestion
		return nil, fmt.Errorf("getting records for domain: %w", err)
```

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/client.go
> +	}
List the number of occurrences you got and what you expect (1) in the error context using `fmt.Errorf("%w: context blabla", errors.ErrListRecords)`

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/client.go
> +	searchedRecord := records.GetRecord(host, recordType)
nit rename `searchedRecord` to `record`

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/client.go
> +	searchedRecord.Destination = ip.String()
nit for explicitness sake

```suggestion
	} else {
		searchedRecord.Destination = ip.String()
	}
```

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/client.go
> +func (c *Client) addAuthParams(domainname string) (*Params, error) {
nit rename `domainname` to `domainName`

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/client.go
> +	}
Isn't this already checked in `Login(ctx context.Context)`

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/client.go
> +	return &params, nil
we can just return something like

```go
	return map[string]string{
		"apikey": c.APIKey,
		"apisessionid": c.Session,
		"customernumber": c.CustomerNumber,
		"domainname": domainname,
	}
```

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/client.go
> +		return nil, err
```suggestion
		return nil, fmt.Errorf("decoding response data: %w", err)
```

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/client.go
> +func (c *Client) InfoDNSRecords(ctx context.Context, domainname string) (*DNSRecordSet, error) {
don't return pointers if there is no need for it

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/client.go
> +func (c *Client) UpdateDNSRecords(ctx context.Context, domain string, records *DNSRecordSet) (*Response, error) {
don't return pointers if there is no need for it

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/client.go
> +	}
nit

```suggestion
	if err != nil {
		return fmt.Errorf("decoding login response data: %w", err)
	} else if loginResponse.Session == "" {
		return fmt.Errorf("%w: in: %s", errors.ErrNoSession, response.ResponseData)
	}

	c.Session = loginResponse.Session
```

2022-09-16 22:19 UTC, qdm12 commented on internal/settings/providers/netcup/client.go
> +func (c *Client) do(ctx context.Context, req *Request) (*Response, error) {
don't return and take arguments as pointers if there is no need for it

2022-10-01 21:57 UTC, qdm12 commented
@Azorimor I pushed changes fixing all the comments above, I have built the image `qmcgaw/ddns-updater:netcup` can you please try it :pray: ? Thanks!

2022-10-03 11:34 UTC, Azorimor commented
Thanks for your feedback. I tested the changes and it did not work. Console Output:
```sh
Running version unknown built on an unknown date (commit unknown)
[...]
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2022/10/03 11:12:24 INFO reading JSON config from file /workspace/data/config.json
2022/10/03 11:12:24 INFO Found single setting to update record
2022/10/03 11:12:24 INFO Reading history from database: domain xxxxx.xx host test
2022/10/03 11:12:24 INFO healthcheck server: listening on 127.0.0.1:9999
2022/10/03 11:12:24 INFO backup: disabled
2022/10/03 11:12:24 INFO http server: listening on :8000
2022/10/03 11:12:24 INFO IP address of test.xxxxx.xx  is 185.yyy.yyy.192 and your IP address is yy.207.1yy.3xx
2022/10/03 11:12:24 INFO Updating record [domain: xxxxx.xx | host: test | provider: netcup | ip: ipv4 or ipv6] to use yy.207.1yy.3xx
2022/10/03 11:12:24 ERROR logging in: session received is empty
```

I am currently bussy. I can look into this in 1-2 weeks. 
The response from the login endpoint of the api looks like this by manually making the request (dummy data):
```json
{
  "serverrequestid": "3FWpNX0RgYY0RNI5=",
  "clientrequestid": "",
  "action": "login",
  "status": "success",
  "statuscode": 2000,
  "shortmessage": "Login successful",
  "longmessage": "Session has been created successful.",
  "responsedata": {
    "apisessionid": "NTg5MzI0MDDDN3Rmc3ZBbW9IYVRqR2JYYYYCUm1RSTUzMVUXXX"
  }
}
```
There is probably something wrong with handling the response data.

I also tested, that the login does work (commonResponse for login request does contain `"ShortMessage" : "Login successfull"`)

2022-10-04 10:21 UTC, qdm12 commented
Thanks for the feedback!

Indeed, fixed in https://github.com/Azorimor/ddns-updater/commit/abf0a1269aeff88e2c0f40629aa0d95ee0c1c210 and re-pushed the image with tag `:netcup`.

2022-10-11 19:57 UTC, qdm12 commented
Hey @Azorimor does the newer image work? I have a report from someone that the netcup log shows it works, but it actually fails and the returned IP address is the older one, not the newer one. Did you experience the same problem?

2022-12-04 23:18 UTC, scrapix commented
Hey @qdm12 first, thank you lots for this great piece of work! 
I have tried to use the docker container with the default compose file and received an error log.

`version: "3.9"
services:
  ddns-updater:
    image: qmcgaw/ddns-updater:netcup
    container_name: ddns-updater
    network_mode: bridge
    ports:
      - 8000:8000/tcp
    volumes:
      - ./data:/updater/data
    environment:
      - CONFIG=
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s

      # Web UI
      - LISTENING_PORT=8000
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_LEVEL=debug
      - LOG_CALLER=hidden
      - SHOUTRRR_ADDRESSES=
    restart: always`

`2022/12/04 23:00:24 INFO reading JSON config from file /updater/data/config.json
2022/12/04 23:00:24 DEBUG config read: {
    "settings": [
      {
        "provider": "netcup",
        "domain": "${myNetcupDomain.de}",
        "host": "@",
        "api_key": "${MyApiKey}",
        "password": "${MyApiPassword}",
        "customer_number": "${MyCustomerNumber}"
      }
    ]
  }
2022/12/04 23:00:24 INFO Found single setting to update record
2022/12/04 23:00:24 INFO Reading history from database: domain ${myNetcupDomain.de} host @
2022/12/04 23:00:24 INFO healthcheck server: listening on 127.0.0.1:9999
2022/12/04 23:00:24 INFO backup: disabled
2022/12/04 23:00:24 INFO http server: listening on :8000
2022/12/04 23:00:24 DEBUG configured to fetch IP: v4 or v6: true, v4: false, v6: false
2022/12/04 23:00:24 DEBUG your public IP address are: v4 or v6: ${0.0.0.0.-current-IP}, v4: <nil>, v6: <nil>
2022/12/04 23:00:24 INFO IP address of ${myNetcupDomain.de} is ${1.2.1.2.-IP-savedAtNetcupCurrently} and your IP address is ${0.0.0.0.-current-IP}
2022/12/04 23:00:24 INFO Updating record [domain: ${myNetcupDomain.de} | host: @ | provider: netcup | ip: ipv4 or ipv6] to use ${0.0.0.0.-current-IP}
2022/12/04 23:00:24 DEBUG POST https://ccp.netcup.net/run/webservice/servers/endpoint.php?JSON | headers: User-Agent: DDNS-Updater quentin.mcgaw@gmail.com | body: {"action":"login","param":{"apikey":"${MyApiKey}","apipassword":"${MyApiPassword}","customernumber":"${MyCustomerNumber}"}}
2022/12/04 23:00:24 DEBUG 200 OK | headers: Cache-Control: no-store, no-cache, must-revalidate, max-age=0,post-check=0, pre-check=0; Pragma: no-cache; X-Xss-Protection: 1; mode=block; Content-Type: application/json; Last-Modified: Sun, 04 Dec 2022 23:00:24 GMT; Date: Sun, 04 Dec 2022 23:00:24 GMT; Expires: Tue, 03 Jul 2001 06:00:00 GMT; Vary: Accept-Encoding,User-Agent; Content-Security-Policy: frame-ancestors 'self';; X-Frame-Options: SAMEORIGIN; X-Content-Type-Options: nosniff; X-Robots-Tag: noindex | body: {"serverrequestid":"${ID}","clientrequestid":"","action":"login","status":"success","statuscode":2000,"shortmessage":"Login successful","longmessage":"Session has been created successful.","responsedata":{"apisessionid":"${SessionID}"}}
2022/12/04 23:00:24 DEBUG POST https://ccp.netcup.net/run/webservice/servers/endpoint.php?JSON | headers: User-Agent: DDNS-Updater quentin.mcgaw@gmail.com | body: {"action":"infoDnsRecords","param":{"apikey":"${MyApiKey}","apisessionid":"${SessionID}","customernumber":"${MyCustomerNumber}","domainname":"${myNetcupDomain.de}"}}
2022/12/04 23:00:24 DEBUG 200 OK | headers: Cache-Control: no-store, no-cache, must-revalidate, max-age=0,post-check=0, pre-check=0; X-Robots-Tag: noindex; X-Frame-Options: SAMEORIGIN; Date: Sun, 04 Dec 2022 23:00:24 GMT; Content-Type: application/json; Expires: Tue, 03 Jul 2001 06:00:00 GMT; Last-Modified: Sun, 04 Dec 2022 23:00:24 GMT; X-Xss-Protection: 1; mode=block; Content-Security-Policy: frame-ancestors 'self';; X-Content-Type-Options: nosniff; Pragma: no-cache; Vary: Accept-Encoding,User-Agent | body: {"serverrequestid":"${ID}","clientrequestid":"","action":"infoDnsRecords","status":"success","statuscode":2000,"shortmessage":"DNS records found","longmessage":"DNS Records for this zone were found.","responsedata":{"dnsrecords":[{"id":"${ID}","hostname":"@","type":"A","priority":"0","destination":"${1.2.1.2.-IP-savedAtNetcupCurrently}","deleterecord":false,"state":"yes"},{"id":"${ID}","hostname":"@","type":"AAAA","priority":"0","destination":"${myIPV6}","deleterecord":false,"state":"yes"},{"id":"${ID}","hostname":"@","type":"TXT","priority":"0","destination":"${destination}","deleterecord":false,"state":"yes"},{"id":"${ID}","hostname":"@","type":"TXT","priority":"0","destination":"${Destination}","deleterecord":false,"state":"yes"},{"id":"${ID}","hostname":"${myNetcupDomain.de}","type":"MX","priority":"10","destination":"mail.${myDomain.de}","deleterecord":false,"state":"yes"},{"id":"${ID}","hostname":"mail.${myNetcupDomain.de}","type":"CNAME","priority":"0","destination":"mail.${myDomain.de}","deleterecord":false,"state":"yes"},{"id":"${ID}","hostname":"p.${myNetcupDomain.de}","type":"A","priority":"0","destination":"${1.2.1.2.-IP-savedAtNetcupCurrently}","deleterecord":false,"state":"yes"},{"id":"${ID}","hostname":"p.${myNetcupDomain.de}","type":"AAAA","priority":"0","destination":"${myIPV6}","deleterecord":false,"state":"yes"}]}}
2022/12/04 23:00:24 DEBUG POST https://ccp.netcup.net/run/webservice/servers/endpoint.php?JSON | headers: User-Agent: DDNS-Updater quentin.mcgaw@gmail.com | body: {"action":"updateDnsRecords","param":{"apikey":"${MyApiKey}","apisessionid":"${SessionID}","customernumber":"${MyCustomerNumber}","domainname":"${myNetcupDomain.de}","dnsrecordset":{"dnsrecords":[{"id":"","destination":"${0.0.0.0.-current-IP}","hostname":"@","priority":"","state":"","type":"A"}]}}}
2022/12/04 23:00:24 DEBUG 200 OK | headers: Date: Sun, 04 Dec 2022 23:00:24 GMT; Pragma: no-cache; X-Frame-Options: SAMEORIGIN; Expires: Tue, 03 Jul 2001 06:00:00 GMT; Content-Security-Policy: frame-ancestors 'self';; Cache-Control: no-store, no-cache, must-revalidate, max-age=0,post-check=0, pre-check=0; Vary: Accept-Encoding,User-Agent; X-Content-Type-Options: nosniff; Content-Type: application/json; Last-Modified: Sun, 04 Dec 2022 23:00:24 GMT; X-Robots-Tag: noindex; X-Xss-Protection: 1; mode=block | body: {"serverrequestid":"${ID}","clientrequestid":"","action":"updateDnsRecords","status":"success","statuscode":2000,"shortmessage":"DNS records successful updated","longmessage":"The given DNS records for this zone were updated.","responsedata":{"dnsrecords":[{"id":"${ID}","hostname":"@","type":"A","priority":"0","destination":"${1.2.1.2.-IP-savedAtNetcupCurrently}","deleterecord":false,"state":"yes"},{"id":"${ID}","hostname":"@","type":"AAAA","priority":"0","destination":"${myIPV6}","deleterecord":false,"state":"yes"},{"id":"${ID}","hostname":"@","type":"A","priority":"0","destination":"${0.0.0.0.-current-IP}","deleterecord":false,"state":"unknown"},{"id":"${ID}","hostname":"@","type":"TXT","priority":"0","destination":"${Destination}","deleterecord":false,"state":"yes"},{"id":"${ID}","hostname":"@","type":"TXT","priority":"0","destination":"${Destination}","deleterecord":false,"state":"yes"},{"id":"${ID}","hostname":"${myNetcupDomain.de}","type":"MX","priority":"10","destination":"mail.${myDomain.de}","deleterecord":false,"state":"yes"},{"id":"${ID}","hostname":"mail.${myNetcupDomain.de}","type":"CNAME","priority":"0","destination":"mail.${myDomain.de}","deleterecord":false,"state":"yes"},{"id":"${ID}","hostname":"p.${myNetcupDomain.de}","type":"A","priority":"0","destination":"${1.2.1.2.-IP-savedAtNetcupCurrently}","deleterecord":false,"state":"yes"},{"id":"${ID}","hostname":"p.${myNetcupDomain.de}","type":"AAAA","priority":"0","destination":"${myIPV6}","deleterecord":false,"state":"yes"}]}}
2022/12/04 23:00:24 ERROR mismatching IP address received: expected ${0.0.0.0.-current-IP} but re [...]

2022-12-06 19:05 UTC, qdm12 commented
Hi @scrapix thanks for the feedback.
Does it actually update it, even though it logs an error?

I saw in the update response data from your logs there are two records:

```json
{"id":"${ID}","hostname":"@","type":"A","priority":"0","destination":"${0.0.0.0.-current-IP}","deleterecord":false,"state":"unknown"},
{"id":"${ID}","hostname":"@","type":"A","priority":"0","destination":"${1.2.1.2.-IP-savedAtNetcupCurrently}","deleterecord":false,"state":"yes"},
```

So it looks like it's adding the record twice, but with the new one in unknown state???

2022-12-06 23:52 UTC, scrapix commented
@qdm12 it did not update the records :/ the other project I've mentioned actually updates the records at (and can create new ones). While not supporting many different providers.

2022-12-07 07:20 UTC, qdm12 commented
I believe I spotted a few JSON decoding programming errors (most likely in my refactor of this branch, so 100% my bad). These are fixed in https://github.com/qdm12/ddns-updater/pull/361/commits/f4714b6aba4539bc3fbef396585a252bfa439026 largely thanks to the logs you attached! :+1: 

I re-pushed image `qmcgaw/ddns-updater:netcup` (amd64 only)

2022-12-09 05:47 UTC, scrapix commented
I'll try asap again!

2023-06-12 10:28 UTC, qdm12 commented
Rebased it on the master branch

2023-06-12 20:36 UTC, Assaro commented
I have been able to test it and it works just fine
```

========================================
========================================
============= ddns-updater =============
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================

Running version unknown built on an unknown date (commit unknown)

📣 Environment variables parsing was changed on 12 June, please report any issue you might have

🔧 Need help? https://github.com/qdm12/ddns-updater/discussions/new
🐛 Bug? https://github.com/qdm12/ddns-updater/issues/new
✨ New feature? https://github.com/qdm12/ddns-updater/issues/new
☕ Discussion? https://github.com/qdm12/ddns-updater/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2023-06-12T20:31:03Z INFO reading JSON config from file /updater/data/config.json
2023-06-12T20:31:03Z INFO Found single setting to update record
2023-06-12T20:31:04Z INFO Reading history from database: domain redacted.com host ddns
2023-06-12T20:31:04Z INFO [healthcheck server] listening on 127.0.0.1:9999
2023-06-12T20:31:04Z INFO [backup] disabled
2023-06-12T20:31:04Z INFO [http server] listening on :8000
2023-06-12T20:31:04Z WARN obtaining ipv4 or ipv6 address: try 1 of 3: no IP address found: from "https://diagnostic.opendns.com/myip"
2023-06-12T20:31:04Z INFO obtaining ipv4 or ipv6 address: succeeded after 2 tries
2023-06-12T20:31:04Z INFO IP address of ddns.redacted.com is 46.38.243.234 and your IP address is 1.1.1.1
2023-06-12T20:31:04Z INFO Updating record [domain: redacted.com | host: ddns | provider: netcup | ip: ipv4 or ipv6] to use 1.1.1.1

```

The IP and domain have been changed for privacy reasons

2023-06-12 21:26 UTC, qdm12 commented
Awesome thanks @Assaro I'll rebase and merge it tomorrow!

2023-06-14 06:11 UTC, qdm12 approved these changes

2023-06-14 06:16 UTC, merged